### ISSUE TITLE
Consider adding a confirmation dialog when using data_sync:push

### ISSUE THREAD

**Issue by mivanek** [d4be4st/mina-data_sync#2]
Since pushing the database to the server is a destructive and potentially irreversible change, some kind of a confirmation dialog would probably be a good idea. I would potentially even require inputting the database name as confirmation. Thoughts?

**Comment by d4be4st** [comment]
Another idea might be to automaticaly do a backup before restoring.

inputting the name as confirmation might be a problem if using secrets, but some random string will be doable.

**Comment by mivanek** [comment]
I think doing a backup is a good idea regardless of the confirmation dialog.

As for the secrets issue, a softer confirmation version that would also be quite useful would be a normal y/n dialog, with the n answer set as default - so you have to manually input y for it to pass.
