### ISSUE TITLE
no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by dimanlin** [d4be4st/mina-data_sync#6]
mina data_sync:pull
-----> Using RVM environment "ruby-2.4.1"
       Using /home/deployer/.rvm/gems/ruby-2.4.1
-----> Dumping database
-----> pg_dump -d airsoft_production -U postgres -O -c > tmp/q-production-2017-06-04.sql
       Connection to 207.154.237.56 closed.

       Elapsed time: 9.27 seconds
-----> Copying backup
-----> Backup: tmp/q-production-2017-06-04.sql
       q-production-2017-06-04.sql
        168,546 100%  160.74MB/s    0:00:00 (xfr#1, to-chk=0/1)
       Elapsed time: 1.12 seconds
-----> Restoring database
       sh: 3: function: not found

       /home/dimanlin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `initialize': no implicit conversion of nil into String (TypeError)

       	from /home/dimanlin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `new'

       	from /home/dimanlin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'

       	from -e:2:in `<main>'

       sh: 34: Syntax error: "}" unexpected

 !     Run Error

**Comment by abhinavc** [comment]
Seeing the same issue in mina-data_sync (1.0.4). Did you find a resolution / workaround?
